/*
 * aida
 *
 * 1.0.366
 *
 * The version of the OpenAPI document: 1.0.366
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Aida.Sdk.Model;
using Aida.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Aida.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing DisplaySystemStatusDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DisplaySystemStatusDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DisplaySystemStatusDto
        //private DisplaySystemStatusDto instance;

        public DisplaySystemStatusDtoTests()
        {
            // TODO uncomment below to create an instance of DisplaySystemStatusDto
            //instance = new DisplaySystemStatusDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DisplaySystemStatusDto
        /// </summary>
        [Fact]
        public void DisplaySystemStatusDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" DisplaySystemStatusDto
            //Assert.IsType<DisplaySystemStatusDto>(instance);
        }


        /// <summary>
        /// Test the property 'ServerStatus'
        /// </summary>
        [Fact]
        public void ServerStatusTest()
        {
            // TODO unit test for the property 'ServerStatus'
        }
        /// <summary>
        /// Test the property 'UpTime'
        /// </summary>
        [Fact]
        public void UpTimeTest()
        {
            // TODO unit test for the property 'UpTime'
        }
        /// <summary>
        /// Test the property 'IpAddress'
        /// </summary>
        [Fact]
        public void IpAddressTest()
        {
            // TODO unit test for the property 'IpAddress'
        }
        /// <summary>
        /// Test the property 'SoftwareVersion'
        /// </summary>
        [Fact]
        public void SoftwareVersionTest()
        {
            // TODO unit test for the property 'SoftwareVersion'
        }

    }

}
