/*
 * aida
 *
 * 1.0.366
 *
 * The version of the OpenAPI document: 1.0.366
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Aida.Sdk.Model;
using Aida.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Aida.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing FeederState
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FeederStateTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FeederState
        //private FeederState instance;

        public FeederStateTests()
        {
            // TODO uncomment below to create an instance of FeederState
            //instance = new FeederState();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FeederState
        /// </summary>
        [Fact]
        public void FeederStateInstanceTest()
        {
            // TODO uncomment below to test "IsType" FeederState
            //Assert.IsType<FeederState>(instance);
        }


        /// <summary>
        /// Test the property 'PositionId'
        /// </summary>
        [Fact]
        public void PositionIdTest()
        {
            // TODO unit test for the property 'PositionId'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

    }

}
