/*
 * aida
 *
 * 1.0.366
 *
 * The version of the OpenAPI document: 1.0.366
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Aida.Sdk.Model;
using Aida.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Aida.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing HomographySettingsDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class HomographySettingsDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for HomographySettingsDto
        //private HomographySettingsDto instance;

        public HomographySettingsDtoTests()
        {
            // TODO uncomment below to create an instance of HomographySettingsDto
            //instance = new HomographySettingsDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of HomographySettingsDto
        /// </summary>
        [Fact]
        public void HomographySettingsDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" HomographySettingsDto
            //Assert.IsType<HomographySettingsDto>(instance);
        }


        /// <summary>
        /// Test the property 'CameraId'
        /// </summary>
        [Fact]
        public void CameraIdTest()
        {
            // TODO unit test for the property 'CameraId'
        }
        /// <summary>
        /// Test the property 'DstPoints'
        /// </summary>
        [Fact]
        public void DstPointsTest()
        {
            // TODO unit test for the property 'DstPoints'
        }
        /// <summary>
        /// Test the property 'SrcPoints'
        /// </summary>
        [Fact]
        public void SrcPointsTest()
        {
            // TODO unit test for the property 'SrcPoints'
        }
        /// <summary>
        /// Test the property 'HomographyMatrix'
        /// </summary>
        [Fact]
        public void HomographyMatrixTest()
        {
            // TODO unit test for the property 'HomographyMatrix'
        }

    }

}
