/*
 * aida
 *
 * 1.0.366
 *
 * The version of the OpenAPI document: 1.0.366
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Aida.Sdk.Model;
using Aida.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Aida.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing JobTemplateLayoutAutoPosSettingsDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class JobTemplateLayoutAutoPosSettingsDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for JobTemplateLayoutAutoPosSettingsDto
        //private JobTemplateLayoutAutoPosSettingsDto instance;

        public JobTemplateLayoutAutoPosSettingsDtoTests()
        {
            // TODO uncomment below to create an instance of JobTemplateLayoutAutoPosSettingsDto
            //instance = new JobTemplateLayoutAutoPosSettingsDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of JobTemplateLayoutAutoPosSettingsDto
        /// </summary>
        [Fact]
        public void JobTemplateLayoutAutoPosSettingsDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" JobTemplateLayoutAutoPosSettingsDto
            //Assert.IsType<JobTemplateLayoutAutoPosSettingsDto>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Index'
        /// </summary>
        [Fact]
        public void IndexTest()
        {
            // TODO unit test for the property 'Index'
        }
        /// <summary>
        /// Test the property 'LayoutId'
        /// </summary>
        [Fact]
        public void LayoutIdTest()
        {
            // TODO unit test for the property 'LayoutId'
        }
        /// <summary>
        /// Test the property 'JobTemplateId'
        /// </summary>
        [Fact]
        public void JobTemplateIdTest()
        {
            // TODO unit test for the property 'JobTemplateId'
        }
        /// <summary>
        /// Test the property 'LayoutName'
        /// </summary>
        [Fact]
        public void LayoutNameTest()
        {
            // TODO unit test for the property 'LayoutName'
        }
        /// <summary>
        /// Test the property 'DisplayName'
        /// </summary>
        [Fact]
        public void DisplayNameTest()
        {
            // TODO unit test for the property 'DisplayName'
        }
        /// <summary>
        /// Test the property 'Threshold'
        /// </summary>
        [Fact]
        public void ThresholdTest()
        {
            // TODO unit test for the property 'Threshold'
        }
        /// <summary>
        /// Test the property 'DebugUrl'
        /// </summary>
        [Fact]
        public void DebugUrlTest()
        {
            // TODO unit test for the property 'DebugUrl'
        }
        /// <summary>
        /// Test the property 'TemplateMatchingConfiguration'
        /// </summary>
        [Fact]
        public void TemplateMatchingConfigurationTest()
        {
            // TODO unit test for the property 'TemplateMatchingConfiguration'
        }
        /// <summary>
        /// Test the property 'IsConfigured'
        /// </summary>
        [Fact]
        public void IsConfiguredTest()
        {
            // TODO unit test for the property 'IsConfigured'
        }

    }

}
