/*
 * aida
 *
 * 1.0.366
 *
 * The version of the OpenAPI document: 1.0.366
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Aida.Sdk.Model;
using Aida.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Aida.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing JobTemplateLayoutDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class JobTemplateLayoutDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for JobTemplateLayoutDto
        //private JobTemplateLayoutDto instance;

        public JobTemplateLayoutDtoTests()
        {
            // TODO uncomment below to create an instance of JobTemplateLayoutDto
            //instance = new JobTemplateLayoutDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of JobTemplateLayoutDto
        /// </summary>
        [Fact]
        public void JobTemplateLayoutDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" JobTemplateLayoutDto
            //Assert.IsType<JobTemplateLayoutDto>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Layout'
        /// </summary>
        [Fact]
        public void LayoutTest()
        {
            // TODO unit test for the property 'Layout'
        }
        /// <summary>
        /// Test the property 'Index'
        /// </summary>
        [Fact]
        public void IndexTest()
        {
            // TODO unit test for the property 'Index'
        }
        /// <summary>
        /// Test the property 'LayoutId'
        /// </summary>
        [Fact]
        public void LayoutIdTest()
        {
            // TODO unit test for the property 'LayoutId'
        }
        /// <summary>
        /// Test the property 'JobTemplateId'
        /// </summary>
        [Fact]
        public void JobTemplateIdTest()
        {
            // TODO unit test for the property 'JobTemplateId'
        }
        /// <summary>
        /// Test the property 'SupportSide'
        /// </summary>
        [Fact]
        public void SupportSideTest()
        {
            // TODO unit test for the property 'SupportSide'
        }
        /// <summary>
        /// Test the property 'AutoPosSettings'
        /// </summary>
        [Fact]
        public void AutoPosSettingsTest()
        {
            // TODO unit test for the property 'AutoPosSettings'
        }

    }

}
