/*
 * aida
 *
 * 1.0.366
 *
 * The version of the OpenAPI document: 1.0.366
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Aida.Sdk.Model;
using Aida.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Aida.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing LampState
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LampStateTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for LampState
        //private LampState instance;

        public LampStateTests()
        {
            // TODO uncomment below to create an instance of LampState
            //instance = new LampState();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LampState
        /// </summary>
        [Fact]
        public void LampStateInstanceTest()
        {
            // TODO uncomment below to test "IsType" LampState
            //Assert.IsType<LampState>(instance);
        }



    }

}
