/*
 * aida
 *
 * 1.0.366
 *
 * The version of the OpenAPI document: 1.0.366
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Aida.Sdk.Model;
using Aida.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Aida.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing LaserBoardConfig
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LaserBoardConfigTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for LaserBoardConfig
        //private LaserBoardConfig instance;

        public LaserBoardConfigTests()
        {
            // TODO uncomment below to create an instance of LaserBoardConfig
            //instance = new LaserBoardConfig();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LaserBoardConfig
        /// </summary>
        [Fact]
        public void LaserBoardConfigInstanceTest()
        {
            // TODO uncomment below to test "IsType" LaserBoardConfig
            //Assert.IsType<LaserBoardConfig>(instance);
        }


        /// <summary>
        /// Test the property 'SerialPortName'
        /// </summary>
        [Fact]
        public void SerialPortNameTest()
        {
            // TODO unit test for the property 'SerialPortName'
        }

    }

}
