/*
 * aida
 *
 * 1.0.366
 *
 * The version of the OpenAPI document: 1.0.366
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Aida.Sdk.Model;
using Aida.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Aida.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing MarkEntitiesResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MarkEntitiesResultTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MarkEntitiesResult
        //private MarkEntitiesResult instance;

        public MarkEntitiesResultTests()
        {
            // TODO uncomment below to create an instance of MarkEntitiesResult
            //instance = new MarkEntitiesResult();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MarkEntitiesResult
        /// </summary>
        [Fact]
        public void MarkEntitiesResultInstanceTest()
        {
            // TODO uncomment below to test "IsType" MarkEntitiesResult
            //Assert.IsType<MarkEntitiesResult>(instance);
        }


        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'ErrorCode'
        /// </summary>
        [Fact]
        public void ErrorCodeTest()
        {
            // TODO unit test for the property 'ErrorCode'
        }

    }

}
