/*
 * aida
 *
 * 1.0.366
 *
 * The version of the OpenAPI document: 1.0.366
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Aida.Sdk.Model;
using Aida.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Aida.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing MySqlDataSourceConfigurationDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MySqlDataSourceConfigurationDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MySqlDataSourceConfigurationDto
        //private MySqlDataSourceConfigurationDto instance;

        public MySqlDataSourceConfigurationDtoTests()
        {
            // TODO uncomment below to create an instance of MySqlDataSourceConfigurationDto
            //instance = new MySqlDataSourceConfigurationDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MySqlDataSourceConfigurationDto
        /// </summary>
        [Fact]
        public void MySqlDataSourceConfigurationDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" MySqlDataSourceConfigurationDto
            //Assert.IsType<MySqlDataSourceConfigurationDto>(instance);
        }


        /// <summary>
        /// Test the property 'TableName'
        /// </summary>
        [Fact]
        public void TableNameTest()
        {
            // TODO unit test for the property 'TableName'
        }
        /// <summary>
        /// Test the property 'QueryTemplate'
        /// </summary>
        [Fact]
        public void QueryTemplateTest()
        {
            // TODO unit test for the property 'QueryTemplate'
        }
        /// <summary>
        /// Test the property 'ConnectionString'
        /// </summary>
        [Fact]
        public void ConnectionStringTest()
        {
            // TODO unit test for the property 'ConnectionString'
        }
        /// <summary>
        /// Test the property 'Provider'
        /// </summary>
        [Fact]
        public void ProviderTest()
        {
            // TODO unit test for the property 'Provider'
        }

    }

}
