/*
 * aida
 *
 * 1.0.366
 *
 * The version of the OpenAPI document: 1.0.366
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Aida.Sdk.Model;
using Aida.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Aida.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing Point2fDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class Point2fDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Point2fDto
        //private Point2fDto instance;

        public Point2fDtoTests()
        {
            // TODO uncomment below to create an instance of Point2fDto
            //instance = new Point2fDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Point2fDto
        /// </summary>
        [Fact]
        public void Point2fDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" Point2fDto
            //Assert.IsType<Point2fDto>(instance);
        }


        /// <summary>
        /// Test the property 'X'
        /// </summary>
        [Fact]
        public void XTest()
        {
            // TODO unit test for the property 'X'
        }
        /// <summary>
        /// Test the property 'Y'
        /// </summary>
        [Fact]
        public void YTest()
        {
            // TODO unit test for the property 'Y'
        }

    }

}
