/*
 * aida
 *
 * 1.0.366
 *
 * The version of the OpenAPI document: 1.0.366
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Aida.Sdk.Model;
using Aida.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Aida.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing ReaderAccessType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ReaderAccessTypeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ReaderAccessType
        //private ReaderAccessType instance;

        public ReaderAccessTypeTests()
        {
            // TODO uncomment below to create an instance of ReaderAccessType
            //instance = new ReaderAccessType();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ReaderAccessType
        /// </summary>
        [Fact]
        public void ReaderAccessTypeInstanceTest()
        {
            // TODO uncomment below to test "IsType" ReaderAccessType
            //Assert.IsType<ReaderAccessType>(instance);
        }



    }

}
