/*
 * aida
 *
 * 1.0.366
 *
 * The version of the OpenAPI document: 1.0.366
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Aida.Sdk.Model;
using Aida.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Aida.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing RuntimeOcrInspectionResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RuntimeOcrInspectionResultTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RuntimeOcrInspectionResult
        //private RuntimeOcrInspectionResult instance;

        public RuntimeOcrInspectionResultTests()
        {
            // TODO uncomment below to create an instance of RuntimeOcrInspectionResult
            //instance = new RuntimeOcrInspectionResult();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RuntimeOcrInspectionResult
        /// </summary>
        [Fact]
        public void RuntimeOcrInspectionResultInstanceTest()
        {
            // TODO uncomment below to test "IsType" RuntimeOcrInspectionResult
            //Assert.IsType<RuntimeOcrInspectionResult>(instance);
        }


        /// <summary>
        /// Test the property 'InspectionName'
        /// </summary>
        [Fact]
        public void InspectionNameTest()
        {
            // TODO unit test for the property 'InspectionName'
        }
        /// <summary>
        /// Test the property 'OcrResult'
        /// </summary>
        [Fact]
        public void OcrResultTest()
        {
            // TODO unit test for the property 'OcrResult'
        }

    }

}
