/*
 * aida
 *
 * 1.0.366
 *
 * The version of the OpenAPI document: 1.0.366
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Aida.Sdk.Model;
using Aida.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Aida.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing SCardShare
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SCardShareTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SCardShare
        //private SCardShare instance;

        public SCardShareTests()
        {
            // TODO uncomment below to create an instance of SCardShare
            //instance = new SCardShare();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SCardShare
        /// </summary>
        [Fact]
        public void SCardShareInstanceTest()
        {
            // TODO uncomment below to test "IsType" SCardShare
            //Assert.IsType<SCardShare>(instance);
        }



    }

}
