/*
 * aida
 *
 * 1.0.366
 *
 * The version of the OpenAPI document: 1.0.366
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Aida.Sdk.Model;
using Aida.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Aida.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing Stream
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class StreamTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Stream
        //private Stream instance;

        public StreamTests()
        {
            // TODO uncomment below to create an instance of Stream
            //instance = new Stream();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Stream
        /// </summary>
        [Fact]
        public void StreamInstanceTest()
        {
            // TODO uncomment below to test "IsType" Stream
            //Assert.IsType<Stream>(instance);
        }


        /// <summary>
        /// Test the property 'CanRead'
        /// </summary>
        [Fact]
        public void CanReadTest()
        {
            // TODO unit test for the property 'CanRead'
        }
        /// <summary>
        /// Test the property 'CanSeek'
        /// </summary>
        [Fact]
        public void CanSeekTest()
        {
            // TODO unit test for the property 'CanSeek'
        }
        /// <summary>
        /// Test the property 'CanTimeout'
        /// </summary>
        [Fact]
        public void CanTimeoutTest()
        {
            // TODO unit test for the property 'CanTimeout'
        }
        /// <summary>
        /// Test the property 'CanWrite'
        /// </summary>
        [Fact]
        public void CanWriteTest()
        {
            // TODO unit test for the property 'CanWrite'
        }
        /// <summary>
        /// Test the property 'Length'
        /// </summary>
        [Fact]
        public void LengthTest()
        {
            // TODO unit test for the property 'Length'
        }
        /// <summary>
        /// Test the property 'Position'
        /// </summary>
        [Fact]
        public void PositionTest()
        {
            // TODO unit test for the property 'Position'
        }
        /// <summary>
        /// Test the property 'ReadTimeout'
        /// </summary>
        [Fact]
        public void ReadTimeoutTest()
        {
            // TODO unit test for the property 'ReadTimeout'
        }
        /// <summary>
        /// Test the property 'WriteTimeout'
        /// </summary>
        [Fact]
        public void WriteTimeoutTest()
        {
            // TODO unit test for the property 'WriteTimeout'
        }

    }

}
