/*
 * aida
 *
 * 1.0.366
 *
 * The version of the OpenAPI document: 1.0.366
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Aida.Sdk.Model;
using Aida.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Aida.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing TaskDescriptor
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TaskDescriptorTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TaskDescriptor
        //private TaskDescriptor instance;

        public TaskDescriptorTests()
        {
            // TODO uncomment below to create an instance of TaskDescriptor
            //instance = new TaskDescriptor();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TaskDescriptor
        /// </summary>
        [Fact]
        public void TaskDescriptorInstanceTest()
        {
            // TODO uncomment below to test "IsType" TaskDescriptor
            //Assert.IsType<TaskDescriptor>(instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'DisplayName'
        /// </summary>
        [Fact]
        public void DisplayNameTest()
        {
            // TODO unit test for the property 'DisplayName'
        }
        /// <summary>
        /// Test the property 'ExpectedDuration'
        /// </summary>
        [Fact]
        public void ExpectedDurationTest()
        {
            // TODO unit test for the property 'ExpectedDuration'
        }
        /// <summary>
        /// Test the property 'Bucket'
        /// </summary>
        [Fact]
        public void BucketTest()
        {
            // TODO unit test for the property 'Bucket'
        }

    }

}
