/*
 * aida
 *
 * 1.0.366
 *
 * The version of the OpenAPI document: 1.0.366
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Aida.Sdk.Model;
using Aida.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Aida.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing TransportModuleState
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TransportModuleStateTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TransportModuleState
        //private TransportModuleState instance;

        public TransportModuleStateTests()
        {
            // TODO uncomment below to create an instance of TransportModuleState
            //instance = new TransportModuleState();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TransportModuleState
        /// </summary>
        [Fact]
        public void TransportModuleStateInstanceTest()
        {
            // TODO uncomment below to test "IsType" TransportModuleState
            //Assert.IsType<TransportModuleState>(instance);
        }


        /// <summary>
        /// Test the property 'ModuleId'
        /// </summary>
        [Fact]
        public void ModuleIdTest()
        {
            // TODO unit test for the property 'ModuleId'
        }
        /// <summary>
        /// Test the property 'SerialNumber'
        /// </summary>
        [Fact]
        public void SerialNumberTest()
        {
            // TODO unit test for the property 'SerialNumber'
        }
        /// <summary>
        /// Test the property '_Configuration'
        /// </summary>
        [Fact]
        public void _ConfigurationTest()
        {
            // TODO unit test for the property '_Configuration'
        }
        /// <summary>
        /// Test the property 'ModuleStatus'
        /// </summary>
        [Fact]
        public void ModuleStatusTest()
        {
            // TODO unit test for the property 'ModuleStatus'
        }
        /// <summary>
        /// Test the property 'ModuleType'
        /// </summary>
        [Fact]
        public void ModuleTypeTest()
        {
            // TODO unit test for the property 'ModuleType'
        }
        /// <summary>
        /// Test the property 'PhotoSensors'
        /// </summary>
        [Fact]
        public void PhotoSensorsTest()
        {
            // TODO unit test for the property 'PhotoSensors'
        }

    }

}
