/*
 * aida
 *
 * 1.0.366
 *
 * The version of the OpenAPI document: 1.0.366
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Aida.Sdk.Model;
using Aida.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Aida.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing TransportState
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TransportStateTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TransportState
        //private TransportState instance;

        public TransportStateTests()
        {
            // TODO uncomment below to create an instance of TransportState
            //instance = new TransportState();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TransportState
        /// </summary>
        [Fact]
        public void TransportStateInstanceTest()
        {
            // TODO uncomment below to test "IsType" TransportState
            //Assert.IsType<TransportState>(instance);
        }


        /// <summary>
        /// Test the property 'IsExecutingCommand'
        /// </summary>
        [Fact]
        public void IsExecutingCommandTest()
        {
            // TODO unit test for the property 'IsExecutingCommand'
        }
        /// <summary>
        /// Test the property 'Modules'
        /// </summary>
        [Fact]
        public void ModulesTest()
        {
            // TODO unit test for the property 'Modules'
        }
        /// <summary>
        /// Test the property 'OccupiedPositions'
        /// </summary>
        [Fact]
        public void OccupiedPositionsTest()
        {
            // TODO unit test for the property 'OccupiedPositions'
        }
        /// <summary>
        /// Test the property 'Feeders'
        /// </summary>
        [Fact]
        public void FeedersTest()
        {
            // TODO unit test for the property 'Feeders'
        }

    }

}
