/*
 * aida
 *
 * 1.0.366
 *
 * The version of the OpenAPI document: 1.0.366
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Aida.Sdk.Model;
using Aida.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Aida.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing WebHooksOptions
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WebHooksOptionsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WebHooksOptions
        //private WebHooksOptions instance;

        public WebHooksOptionsTests()
        {
            // TODO uncomment below to create an instance of WebHooksOptions
            //instance = new WebHooksOptions();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WebHooksOptions
        /// </summary>
        [Fact]
        public void WebHooksOptionsInstanceTest()
        {
            // TODO uncomment below to test "IsType" WebHooksOptions
            //Assert.IsType<WebHooksOptions>(instance);
        }


        /// <summary>
        /// Test the property 'AckTimeout'
        /// </summary>
        [Fact]
        public void AckTimeoutTest()
        {
            // TODO unit test for the property 'AckTimeout'
        }
        /// <summary>
        /// Test the property 'ExecutionTimeout'
        /// </summary>
        [Fact]
        public void ExecutionTimeoutTest()
        {
            // TODO unit test for the property 'ExecutionTimeout'
        }
        /// <summary>
        /// Test the property 'MaxConnectionRetries'
        /// </summary>
        [Fact]
        public void MaxConnectionRetriesTest()
        {
            // TODO unit test for the property 'MaxConnectionRetries'
        }
        /// <summary>
        /// Test the property 'UseSystemWideWebhooks'
        /// </summary>
        [Fact]
        public void UseSystemWideWebhooksTest()
        {
            // TODO unit test for the property 'UseSystemWideWebhooks'
        }
        /// <summary>
        /// Test the property 'SystemWideWebhookTarget'
        /// </summary>
        [Fact]
        public void SystemWideWebhookTargetTest()
        {
            // TODO unit test for the property 'SystemWideWebhookTarget'
        }

    }

}
