/*
 * aida
 *
 * 1.0.366
 *
 * The version of the OpenAPI document: 1.0.366
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Aida.Sdk.Model;
using Aida.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Aida.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing WorkflowSchedulerStateDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WorkflowSchedulerStateDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WorkflowSchedulerStateDto
        //private WorkflowSchedulerStateDto instance;

        public WorkflowSchedulerStateDtoTests()
        {
            // TODO uncomment below to create an instance of WorkflowSchedulerStateDto
            //instance = new WorkflowSchedulerStateDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WorkflowSchedulerStateDto
        /// </summary>
        [Fact]
        public void WorkflowSchedulerStateDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" WorkflowSchedulerStateDto
            //Assert.IsType<WorkflowSchedulerStateDto>(instance);
        }


        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Errors'
        /// </summary>
        [Fact]
        public void ErrorsTest()
        {
            // TODO unit test for the property 'Errors'
        }
        /// <summary>
        /// Test the property 'QueueSize'
        /// </summary>
        [Fact]
        public void QueueSizeTest()
        {
            // TODO unit test for the property 'QueueSize'
        }
        /// <summary>
        /// Test the property 'QueuedOrderIds'
        /// </summary>
        [Fact]
        public void QueuedOrderIdsTest()
        {
            // TODO unit test for the property 'QueuedOrderIds'
        }
        /// <summary>
        /// Test the property 'ErrorDetails'
        /// </summary>
        [Fact]
        public void ErrorDetailsTest()
        {
            // TODO unit test for the property 'ErrorDetails'
        }
        /// <summary>
        /// Test the property 'LastLoadedItemId'
        /// </summary>
        [Fact]
        public void LastLoadedItemIdTest()
        {
            // TODO unit test for the property 'LastLoadedItemId'
        }
        /// <summary>
        /// Test the property 'UpTimeSeconds'
        /// </summary>
        [Fact]
        public void UpTimeSecondsTest()
        {
            // TODO unit test for the property 'UpTimeSeconds'
        }
        /// <summary>
        /// Test the property 'CurrentJobTemplate'
        /// </summary>
        [Fact]
        public void CurrentJobTemplateTest()
        {
            // TODO unit test for the property 'CurrentJobTemplate'
        }
        /// <summary>
        /// Test the property 'WorkflowTypeName'
        /// </summary>
        [Fact]
        public void WorkflowTypeNameTest()
        {
            // TODO unit test for the property 'WorkflowTypeName'
        }
        /// <summary>
        /// Test the property 'SessionId'
        /// </summary>
        [Fact]
        public void SessionIdTest()
        {
            // TODO unit test for the property 'SessionId'
        }

    }

}
