/*
 * aida
 *
 * 1.0.366
 *
 * The version of the OpenAPI document: 1.0.366
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Aida.Sdk.Client.FileParameter;
using OpenAPIDateConverter = Aida.Sdk.Client.OpenAPIDateConverter;

namespace Aida.Sdk.Model
{
    /// <summary>
    /// Defines BoxModuleConfiguration
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum BoxModuleConfiguration
    {
        /// <summary>
        /// Enum Basic for value: Basic
        /// </summary>
        [EnumMember(Value = "Basic")]
        Basic = 1,

        /// <summary>
        /// Enum SingleFeederOnBoard for value: SingleFeederOnBoard
        /// </summary>
        [EnumMember(Value = "SingleFeederOnBoard")]
        SingleFeederOnBoard = 2,

        /// <summary>
        /// Enum SingleFeeder for value: SingleFeeder
        /// </summary>
        [EnumMember(Value = "SingleFeeder")]
        SingleFeeder = 3,

        /// <summary>
        /// Enum DoubleFeeder for value: DoubleFeeder
        /// </summary>
        [EnumMember(Value = "DoubleFeeder")]
        DoubleFeeder = 4,

        /// <summary>
        /// Enum SingleChipReader for value: SingleChipReader
        /// </summary>
        [EnumMember(Value = "SingleChipReader")]
        SingleChipReader = 5,

        /// <summary>
        /// Enum SingleRfIdReader for value: SingleRfIdReader
        /// </summary>
        [EnumMember(Value = "SingleRfIdReader")]
        SingleRfIdReader = 6,

        /// <summary>
        /// Enum SingleChipAndRfIdReader for value: SingleChipAndRfIdReader
        /// </summary>
        [EnumMember(Value = "SingleChipAndRfIdReader")]
        SingleChipAndRfIdReader = 7,

        /// <summary>
        /// Enum MultiChipLowerBoard for value: MultiChipLowerBoard
        /// </summary>
        [EnumMember(Value = "MultiChipLowerBoard")]
        MultiChipLowerBoard = 8,

        /// <summary>
        /// Enum MultiChipHigherBoard for value: MultiChipHigherBoard
        /// </summary>
        [EnumMember(Value = "MultiChipHigherBoard")]
        MultiChipHigherBoard = 9,

        /// <summary>
        /// Enum MagStripeReader for value: MagStripeReader
        /// </summary>
        [EnumMember(Value = "MagStripeReader")]
        MagStripeReader = 10,

        /// <summary>
        /// Enum InkJetPrinter for value: InkJetPrinter
        /// </summary>
        [EnumMember(Value = "InkJetPrinter")]
        InkJetPrinter = 11,

        /// <summary>
        /// Enum SingleStackerOnBoard for value: SingleStackerOnBoard
        /// </summary>
        [EnumMember(Value = "SingleStackerOnBoard")]
        SingleStackerOnBoard = 12,

        /// <summary>
        /// Enum SingleStacker for value: SingleStacker
        /// </summary>
        [EnumMember(Value = "SingleStacker")]
        SingleStacker = 13,

        /// <summary>
        /// Enum DoubleStacker for value: DoubleStacker
        /// </summary>
        [EnumMember(Value = "DoubleStacker")]
        DoubleStacker = 14

    }

}
