/*
 * aida
 *
 * 1.0.366
 *
 * The version of the OpenAPI document: 1.0.366
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Aida.Sdk.Client.FileParameter;
using OpenAPIDateConverter = Aida.Sdk.Client.OpenAPIDateConverter;

namespace Aida.Sdk.Model
{
    /// <summary>
    /// SamLightOptions
    /// </summary>
    [DataContract(Name = "SamLightOptions")]
    public partial class SamLightOptions : IEquatable<SamLightOptions>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SamLightOptions" /> class.
        /// </summary>
        /// <param name="prefixEntities">prefixEntities.</param>
        public SamLightOptions(bool prefixEntities = default(bool))
        {
            this.PrefixEntities = prefixEntities;
        }

        /// <summary>
        /// Gets or Sets PrefixEntities
        /// </summary>
        [DataMember(Name = "prefixEntities", EmitDefaultValue = true)]
        public bool PrefixEntities { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SamLightOptions {\n");
            sb.Append("  PrefixEntities: ").Append(PrefixEntities).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SamLightOptions);
        }

        /// <summary>
        /// Returns true if SamLightOptions instances are equal
        /// </summary>
        /// <param name="input">Instance of SamLightOptions to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SamLightOptions input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.PrefixEntities == input.PrefixEntities ||
                    this.PrefixEntities.Equals(input.PrefixEntities)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.PrefixEntities.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
