/*
 * aida
 *
 * 1.0.366
 *
 * The version of the OpenAPI document: 1.0.366
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Aida.Sdk.Client.FileParameter;
using OpenAPIDateConverter = Aida.Sdk.Client.OpenAPIDateConverter;

namespace Aida.Sdk.Model
{
    /// <summary>
    /// ScannerEntityMarkFlagsDto
    /// </summary>
    [DataContract(Name = "ScannerEntityMarkFlagsDto")]
    public partial class ScannerEntityMarkFlagsDto : IEquatable<ScannerEntityMarkFlagsDto>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ScannerEntityMarkFlagsDto" /> class.
        /// </summary>
        /// <param name="markContour">markContour.</param>
        /// <param name="markHatch">markHatch.</param>
        public ScannerEntityMarkFlagsDto(bool? markContour = default(bool?), bool? markHatch = default(bool?))
        {
            this.MarkContour = markContour;
            this.MarkHatch = markHatch;
        }

        /// <summary>
        /// Gets or Sets MarkContour
        /// </summary>
        [DataMember(Name = "markContour", EmitDefaultValue = true)]
        public bool? MarkContour { get; set; }

        /// <summary>
        /// Gets or Sets MarkHatch
        /// </summary>
        [DataMember(Name = "markHatch", EmitDefaultValue = true)]
        public bool? MarkHatch { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ScannerEntityMarkFlagsDto {\n");
            sb.Append("  MarkContour: ").Append(MarkContour).Append("\n");
            sb.Append("  MarkHatch: ").Append(MarkHatch).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ScannerEntityMarkFlagsDto);
        }

        /// <summary>
        /// Returns true if ScannerEntityMarkFlagsDto instances are equal
        /// </summary>
        /// <param name="input">Instance of ScannerEntityMarkFlagsDto to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ScannerEntityMarkFlagsDto input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.MarkContour == input.MarkContour ||
                    (this.MarkContour != null &&
                    this.MarkContour.Equals(input.MarkContour))
                ) && 
                (
                    this.MarkHatch == input.MarkHatch ||
                    (this.MarkHatch != null &&
                    this.MarkHatch.Equals(input.MarkHatch))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.MarkContour != null)
                {
                    hashCode = (hashCode * 59) + this.MarkContour.GetHashCode();
                }
                if (this.MarkHatch != null)
                {
                    hashCode = (hashCode * 59) + this.MarkHatch.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
