/*
 * aida
 *
 * 1.0.366
 *
 * The version of the OpenAPI document: 1.0.366
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using Aida.Sdk.Client;
using Aida.Sdk.Api;
// uncomment below to import models
//using Aida.Sdk.Model;

namespace Aida.Sdk.Test.Api
{
    /// <summary>
    ///  Class for testing MachineEventsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class MachineEventsApiTests : IDisposable
    {
        private MachineEventsApi instance;

        public MachineEventsApiTests()
        {
            instance = new MachineEventsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MachineEventsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' MachineEventsApi
            //Assert.IsType<MachineEventsApi>(instance);
        }

        /// <summary>
        /// Test LaserBoardStateChanged
        /// </summary>
        [Fact]
        public void LaserBoardStateChangedTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //LaserBoardStateChangedEventNotification laserBoardStateChangedEventNotification = null;
            //instance.LaserBoardStateChanged(laserBoardStateChangedEventNotification);
        }
    }
}
